create table public.stock (
  id bigint generated by default as identity not null,
  item_id integer null,
  quantity bigint null,
  constraint stock_pkey primary key (id),
  constraint stock_item_id_fkey foreign KEY (item_id) references items (id)
) TABLESPACE pg_default;