create table public.orders (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  item_id integer not null,
  quantity bigint not null,
  constraint orders_pkey primary key (id),
  constraint orders_item_id_fkey foreign KEY (item_id) references items (id)
) TABLESPACE pg_default;