create table public.orders (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    item_id bigint null,
    quantity bigint null,
    "familyFriendly" bigint null,
    constraint orders_pkey primary key (id),
    constraint orders_familyFriendly_fkey foreign KEY ("familyFriendly") references items (id),
    constraint orders_item_id_fkey foreign KEY (item_id) references items (id)
) TABLESPACE pg_default;