create table public.orders (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id text not null,
  items bigint[] not null,
  quantity bigint[] not null,
  constraint orders_pkey primary key (id)
) TABLESPACE pg_default;