create table public.order_groups (
  id bigint generated by default as identity not null,
  user_id text null,
  ordered_at timestamp with time zone null default now(),
  delivery_address text null,
  full_name text null,
  total_cost bigint null,
  constraint order_groups_pkey primary key (id)
) TABLESPACE pg_default;