create table public.orders (
   id bigint generated by default as identity not null,
   item_id bigint null,
   quantity bigint null,
   order_group_id bigint not null,
   status text not null default 'pending'::text,
   constraint orders_pkey primary key (id),
   constraint orders_order_group_id_fkey foreign KEY (order_group_id) references order_groups (id) on update CASCADE on delete CASCADE,
   constraint orders_item_id_fkey foreign KEY (item_id) references items (id)
) TABLESPACE pg_default;