create table public.order_groups (
 id bigint generated by default as identity not null,
 user_id bigint null,
 ordered_at timestamp with time zone null default now(),
 constraint order_groups_pkey primary key (id)
) TABLESPACE pg_default;