CREATE TYPE order_status AS ENUM ('Awaiting Confirmation', 'Shipping', 'Cancelled', 'Processing', 'Confirmed');
create table public.orders (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  item_id bigint null,
  quantity bigint null,
  "familyFriendly" bigint null,
  group_id bigint null,
  status order_status NOT NULL DEFAULT 'Awaiting Confirmation',
  constraint orders_pkey primary key (id),
  constraint orders_group_id_fkey foreign KEY (group_id) references order_groups (id)
) TABLESPACE pg_default;