create table public.verification_requests (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  org_id text not null,
  name text null,
  email text null,
  description text null,
  "productInfo" text null,
  "shippingMethod" text null,
  constraint verification_requests_pkey primary key (id),
  constraint verification_requests_org_id_fkey foreign KEY (org_id) references orgs (id)
) TABLESPACE pg_default;