create table public.browsing_history (
  id bigserial not null,
  item_id bigint not null,
  viewed_at timestamp with time zone not null default now(),
  session_id bigint generated by default as identity not null,
  constraint browsing_history_pkey primary key (id),
  constraint browsing_history_item_id_key unique (item_id),
  constraint browsing_history_item_id_fkey foreign KEY (item_id) references items (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;