create table public.organisations (
                                      id bigint generated by default as identity not null,
                                      name text not null,
                                      created_at timestamp with time zone not null default now(),
                                      description text null,
                                      email text null,
                                      telephone text null,
                                      website text null,
                                      address text null,
                                      is_verified boolean not null default false,
                                      constraint organisations_pkey primary key (id),
                                      constraint organisations_email_key unique (email),
                                      constraint organisations_email_check check ((length(email) <= 254)),
                                      constraint organisations_telephone_check check (
                                          (
                                              (length(telephone) <= 20)
                                                  and (telephone ~ '^[0-9]+$'::text)
                                              )
                                          ),
                                      constraint organisations_website_check check ((length(website) <= 253))
) TABLESPACE pg_default;