create table public.items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  image text null default 'https://dummyimage.com/500x500/fff/000.png'::text,
  price double precision null,
  description text null default 'No Description Provided'::text,
  category text null,
  discount bigint null,
  org_id text null,
  constraint items_pkey primary key (id),
  constraint items_discount_check check (
      (
          (discount > 0)
              and (discount < 101)
          )
      ),
  constraint items_price_check check ((price > (0)::double precision))
) TABLESPACE pg_default;