create table public.reviews (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    item_id bigint not null,
    rating bigint not null,
    "reviewText" text null,
    constraint reviews_pkey primary key (id),
    constraint reviews_item_id_fkey foreign KEY (item_id) references items (id)
) TABLESPACE pg_default;