import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import Providers from "@/app/components/global/Providers";
import { stackServerApp } from "../stack";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Header from "@/app/components/global/Header";
import Footer from "@/app/components/global/Footer";
import ClickTrackerWrapper from "@/app/components/wrappers/ClickTrackerWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><StackProvider app={stackServerApp}>
          <Providers>
      <StackTheme>
          <ClickTrackerWrapper>
              <Header/>
              {children}
              <Footer/>
          </ClickTrackerWrapper>
        </StackTheme>
              </Providers>
      </StackProvider></body>
    </html>
  );
}
