import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { ThemeProvider } from "next-themes";
import { stackServerApp } from "../stack";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Header from "@/app/components/global/Header";
import Footer from "@/app/components/global/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><StackProvider app={stackServerApp}>
          <ThemeProvider>
      <StackTheme>
          <Header/>
                {children}
          <Footer/>
        </StackTheme>
              </ThemeProvider>
      </StackProvider></body>
    </html>
  );
}
